# Generated by Django 4.2 on 2023-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="searchQuery",
            fields=[
                (
                    "searchQuery",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("searchCount", models.IntegerField(default=0)),
            ],
        ),
    ]
