# Generated by Django 4.2.1 on 2023-08-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchQuery',
        ),
    ]
