# Generated by Django 4.2 on 2023-07-03 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
        ("prod_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="usersubscription",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Premium", models.BooleanField(default="False")),
                ("Basic", models.BooleanField(default="False")),
                ("Premium_Expiration", models.DateField(blank=True, null=True)),
                ("Basic_Expiration", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="Postal_Code",
            field=models.CharField(max_length=6),
        ),
    ]
