# Generated by Django 4.2 on 2023-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prod_management", "0002_usersubscription_alter_usersettings_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
