# Generated by Django 4.2 on 2023-07-08 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
        ("prod_management", "0005_remove_subscription_recurring"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOSChecked",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="toschecked",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("TOS_Checked", models.BooleanField(default="False")),
            ],
        ),
    ]
