# Generated by Django 4.2 on 2023-07-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prod_management", "0006_toschecked"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
