# Generated by Django 4.2 on 2023-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prod_management", "0007_subscription_subscription_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_image_path",
            field=models.CharField(default="temp", max_length=100),
            preserve_default=False,
        ),
    ]
