# Generated by Django 4.2 on 2023-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prod_management", "0008_subscription_subscription_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=100)),
                ("user_first_name", models.CharField(max_length=100)),
                ("user_last_name", models.CharField(max_length=100)),
                ("user_message", models.CharField(max_length=1000)),
                ("user_phone_number", models.CharField(max_length=100)),
            ],
        ),
    ]
