# Generated by Django 4.2 on 2023-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prod_management", "0009_usercontactrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_version",
            field=models.CharField(default="Standard", max_length=100),
            preserve_default=False,
        ),
    ]
