# Generated by Django 4.2 on 2023-07-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="bundle",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="media",
            field=models.JSONField(default=list),
        ),
    ]
