# Generated by Django 4.2.1 on 2023-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmade',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpaymentmade',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
