# Generated by Django 4.2 on 2023-06-24 15:03

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaRatings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.IntegerField()),
                ("user_id", models.JSONField(verbose_name=user_auth.models.CustomUser)),
                ("rating", models.FloatField()),
                ("type", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
