# Generated by Django 4.2 on 2023-06-13 04:11

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaratings",
            name="user",
        ),
        migrations.AddField(
            model_name="mediaratings",
            name="user_id",
            field=models.JSONField(default=0, verbose_name=user_auth.models.CustomUser),
            preserve_default=False,
        ),
    ]
