# Generated by Django 4.2 on 2023-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediaratings",
            old_name="type",
            new_name="media_type",
        ),
        migrations.AddField(
            model_name="mediaratings",
            name="streaming_providers",
            field=models.JSONField(default=list),
        ),
    ]
