# Generated by Django 4.2 on 2023-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_remove_mediaratings_user_mediaratings_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaratings",
            name="type",
            field=models.CharField(default="movie", max_length=10),
            preserve_default=False,
        ),
    ]
